### ISSUE TITLE
Where is the game gone?

### ISSUE THREAD

**Issue by segmentationfaulter** [hgarc014/git-game#13]
There is nothing in master branch except a license and a readme file, where are the game files?

**Comment by marado** [comment]
You need to READ the README :-)

**Comment by segmentationfaulter** [comment]
thank marado, it would be great if you add clues to your questions, like some stuff to read, thus the game will not only be playable for the folks who already know how git works.

**Comment by mallowigi** [comment]
I agree. If I didn't know about git blame and git tag I would have already left the game

**Comment by hgarc014** [comment]
I have added some links to help people that are not familiar with git
