### ISSUE TITLE
CHEATS! or might be called TIPS!

### ISSUE THREAD

**Issue by rhoit** [hgarc014/git-game#15]
I guess we can avoid few things... skipping steps!

* `outputclue.sh` can be by passed easily, without resolving the conflict! (sorry i'm not telling how)
* you can change the to desier branch without removed tags.
* @hgarc014 thanx for the awesome game!
![screenshot29](https://cloud.githubusercontent.com/assets/1684754/5690923/52519cfe-98d3-11e4-9993-1126f172a6b8.png)

**Comment by rhoit** [comment]
@hgarc014  just curious i never entered so many branches.. are you still developing it?
branch `keyboard` ( guessing i missed this one ) is this in current game play?

**Comment by hgarc014** [comment]
@rhoit Yes, you can skip some things. The game is completed. However, I may have not removed some of the older branches that are not useful anymore.
