### ISSUE TITLE
./outputclue.sh not working correctly on Yosemite

### ISSUE THREAD

**Issue by stevenbuccini** [hgarc014/git-game#17]
Running the ./outputclue.sh script on master results in:

```bash
/git-game $ ./outputclue.sh nextclue_input.cpp
./outputclue.sh: line 22: md5sum: command not found
./outputclue.sh: line 22: [: =: unary operator expected
./outputclue.sh: line 22: md5sum: command not found
....
```

This block of code runs because `if [[  "$OSTYPE" = "darwin" ]]` fails. In my terminal, `$ $OSTYPE` returns `darwin14`.

**Comment by dsernst** [comment]
Likewise. :+1:  Manually changing the conditional to test against darwin14 seems to have fixed this.

**Comment by StefanScherer** [comment]
I have the same problem. I fixed it this way:

```bash
if [[ "$OSTYPE" =~ ^darwin* ]];then
```

**Comment by hgarc014** [comment]
see #18
