### ISSUE TITLE
Working of Open Badge assignment

### ISSUE THREAD

**Issue by pravj** [hgarc014/git-game#21]
Hey @hgarc014,

It was a nice little game but now when I'm done with it, I'm confused that how to use the `open badge` thing.

It is asking to `Attach Evidence` as `You can attach evidence of your achievement to the badge. Evidence can either be an URL or a file.` but I'm not getting it that what it is asking for?

Can you help me here?

**Comment by hgarc014** [comment]
It is completely up to you. You could put the link showing you completed it, maybe a picture of the site that you completed it. It's completely your choice.
