### ISSUE TITLE
Can see no branches on level 1

### ISSUE THREAD

**Issue by Ulca** [hgarc014/git-game#28]
After I've cloned the project 
$ git branch 
shows only the master branch - am I doing something wrong or is the branch simply not there?

**Comment by robertwhitebit** [comment]
@Ulca 

No, you aren't doing something wrong and you are right, there is no branch Level 1.

Lets take a look at the Readme again :wink: 

> ...
> Your first task is to checkout the commit whose commit message is the answer to this question:
> 
> > When a programmer is born, what is the first thing he/she learns to say?

See you on level 2! :smirk_cat:

**Comment by Ulca** [comment]
ooook :) I simply didn't get the clue - don't know the joke or smth. Thanks for the answer - and for the game :)
