### ISSUE TITLE
MEM 课程建设

### ISSUE THREAD

**Issue by 946598537** [hgarc014/git-game#29]
用于MEM入学导引课

**Comment by hgarc014** [comment]
Sorry, I don't speak that language, but google translate appears to say "Admission guide for MEM lesson", which I do not understand.

对不起，我不会说那种语言，但谷歌翻译出现说“入学指南MEM课” ，我不明白。

**Comment by wizicer** [comment]
Let me explain, he roughly want this game to be a Mandatory Lesson of Master of Engineering Management, however, I don't think it's proper for this repository to be targeted to such specific mission.
I just suggest to close this issue.

**Comment by hgarc014** [comment]
i see, thanks
