### ISSUE TITLE
Can't get beyond 'diff'

### ISSUE THREAD

**Issue by binnyva** [hgarc014/git-game#3]
When I diff the two commits, I get this...

-Sn The Next Clue Is: YtrydjKsYqebDoI3h bTINUeV6 pTVY8jnK2re HRwwNy25Ps6 u0YChCo5Jtw N3xkH3G nx aGo6yQTW RVZMsf3xk tBL0sG9GAR HQbyGYdqs i6dx1fyIPGJVciz8Z1NzdrvGE CKgkFauXqfKJmas cDLerWvBTRzUikmP2 0sqk2Xhie2DcIv KtCyYTlNx7WxJp6A2yox3r aJX4r7FpUhgsyGIwc prCCNx46GKVgzaerab
+Sn The next clue is: YtrydjKsYqebDoI3h bTINUeV6 pTVY8jnK2re HRwwNy25Ps6 u0YChCo5Jtw N3xkH3G nx aGo6yQTW RVZMsf3xk tBL0sG9GAR HQbyGYdqs i6dx1fyIPGJVciz8Z1NzdrvGE CKgkFauXqfKJmas cDLerWvBTRzUikmP2 0sqk2Xhie2DcIv KtCyYTlNx7WxJp6A2yox3r aJX4r7FpUhgsyGIwc prCCNx46GKVgzaerab

Not clear what I should be doing next. Am I missing something?

**Comment by medains** [comment]
Read the README.md more carefully

**Comment by mbubb** [comment]
I muddled my way through this one until I found legibility...

How shoudl I know which commits to diff?

**Comment by mriehl** [comment]
@mbubb the idea is to diff a file and not a specific commit. I think it's even stated in the hint.

**Comment by jplatte** [comment]
The README.md said something about a different branch we were on already that also has the file we want to diff, I thought I should make a diff of two branches. I'll just try to diff the file with various older commits after reading this though... I don't really get it but the game has been fun up to this point already :)

**Comment by mriehl** [comment]
Yeah I actually had to redo the whole thing because I didn't notice the file in one of the earlier branches. Diffing the file with the other branch's file worked fine though.

**Comment by jplatte** [comment]
What? This file does exist in another branch? :D
Which one??

**Comment by mriehl** [comment]
Well I'm not writing the solution here but it's one you have to check out at some point (it's the one with the data structure related to maps IIRC)

**Comment by jplatte** [comment]
Haha, found it right before reading your comment. It's the very first one you check out though, not the thing having to do with data structure stuff.

**Comment by hgarc014** [comment]
closing since this has been resolved...

**Comment by dawoodjee** [comment]
Damn, this isnt suppose to take me 6 whole freakin hours, is it? BTW I already checked out that branch and saw that new message which keeps telling me to do the things I already did. I'm in a checkout infinite loop :'(
