### ISSUE TITLE
New game request

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [hgarc014/git-game#38]
This is great for folks who already know their way around git. It is, of course, a test of git skills. The problem is that it assumes a certain familiarity with git. The links in the README are useful, but not all that much for people (like me) who are new to git.

Can we get a git skills trainer game for git beginners? That would be awesome.

Thanks.

**Comment by hgarc014** [comment]
That's an interesting idea, but I feel that git is fairly simple. Something easier than what it is now would kinda be more like a tutorial, and there is a lot of tutorials online.

**Comment by ParaplegicRacehorse** [comment]
True but, honestly, I wasn't able to get past the first mission; even with the help of a cheatsheet. I'm new to git. I can clone, commit, push, pull, branch, checkout, and sometimes I even can remember how to merge branches. Examining commit histories is beyond me and is NOT an introductory skill.

So a tutorial on the basics - clone, push, pull, branch, checkout - okay, not necessary because there are plenty of very good ones, some of which are interactive. Getting into merging and commit histories, though, I haven't found any good training material out there. I _have_ been looking, but not very hard.

Perhaps it would be enough to link to intro tuts and other training sources from the README? Something like

[source,asciidoc]
----
== Git Beginners
This is game not __yet__ for you. To play, you will need to know the following:

.Needed Skills
* Basics - clone, commit, push, pull
* Moderate - diff and merge
* Moderate-Advanced - examine and roll back commits and other historical events

If you can't already do these things, there are good training materials for this.

.Training Resources
* http://someplace[someplace]
* http://someotherplace[someotherplace]
* http://placethree[placethree]
* etc...
----

**Comment by hgarc014** [comment]
I understand, but I think part of the fun of the game is figuring out what you need to do on your own. Often times people are going to present you with a problem, and you have to figure out the solution. 

I agree that a list of training resources would be nice, but it also gives away solutions without effort. For instance a few quick searches lead to:

**git history**

https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History

**git merging**

https://git-scm.com/docs/git-merge

 **examine and roll back commits and other historical events**

https://github.com/blog/2019-how-to-undo-almost-anything-with-git

Which provide some useful information that help  with levels.

**Comment by ParaplegicRacehorse** [comment]
Oh, how many times I have tried to understand whatever jargon git-scm is written in; and failed; miserably. That book is written by a programmer, for programmers. Pro Git is better, but still not good. Someone should write "Git for Laymen". I'm a non-technical writer who uses git to handily keep versioned backups of my writing. I thought git-game could make an interesting distraction, periodically, when I need one; and teach me something new at the same time.

I was wrong. What I need is https://vim-adventures.com[vim-adventures] for git.

I consider the issue closed.

**Comment by hgarc014** [comment]
I completely understand, but I'm busy right now. I'll definitely consider it in the future though
