### ISSUE TITLE
how to answer question?

### ISSUE THREAD

**Issue by wenpengwu** [hgarc014/git-game#42]
i don`t know how to start the game. sorry, this question may be  stupid .

**Comment by chinesedfan** [comment]
Type git commands as README.md says. And you will find hits of the next level.

**Comment by wenpengwu** [comment]
thanks , i have knew

**Comment by yansheng836** [comment]
Excuse me, I also don't seem to know how to play this game, and the website is not accessible, can you give a demo like gif or other?

**Comment by yansheng836** [comment]
I seem to know how to use it, but I still feel the need to give a demo that allows first-time users to get started quickly and enjoy it.
