### ISSUE TITLE
outputclue.sh doesn't work on Windows

### ISSUE THREAD

**Issue by InPermutation** [hgarc014/git-game#8]
Don't want to give away anything, but it's the same error no matter what you use in place of `FILE` here:
```
C:\code\git-game>./outputclue.sh FILE 
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by hgarc014** [comment]
Yes, windows doesn't use bash. 
Currently, I don't think you would be able to run the bash files in the game unless you install Cygwin as suggested here: http://stackoverflow.com/a/6413405/3926051

If the above suggestion works or doesn't work, please let me know. I'll think about a more universal solution.

**Comment by InPermutation** [comment]
Yes; calling over to `bash` works with this syntax:

```
C:\code\git-game> bash -c 'cd /c/code/git-game ; ./outputclue.sh FILE'
```

So does opening a `bash` prompt and executing it there:

```
C:\code\git-game>bash
bash-3.1$ cd /c/code/git-game
bash-3.1$ ./outputclue.sh FILE
```

I think this issue and issue #2 can both be solved with a similar solution.

**Comment by thantos** [comment]
If you grab the text, put it in a new file, then use certutil to decode it, it works :).

I made it through the game with windows and notepad (lazy).

**Comment by riqpe** [comment]
Maybe add text on master README telling people on windows to use Cygwin.

**Comment by russell-miller** [comment]
If you're using the Windows Git, I'd suggest using the "Git Bash" program that it ships with. It behaves pretty much exactly like bash and has several linux utilities included.

**Comment by InPermutation** [comment]
Yeah; git bash is actually what was on my `%PATH%`, so I can confirm it works perfectly for this question.

**Comment by samfishman** [comment]
Also most Macs have `md5` instead of `md5sum`, which causes a separate issue with `outputclue.sh`.

**Comment by hgarc014** [comment]
@samfishman I believe I just fixed that issue.
@InPermutation i'll add the additional information to the README for windows users.

**Comment by hgarc014** [comment]
done
