### ISSUE TITLE
outputclue.sh not compatible with OS X

### ISSUE THREAD

**Issue by aceysmith** [hgarc014/git-game#9]
The two key issues being OS X's native md5 command is 'md5' not 'md5sum', and the base64 command needs -D to decode the input.

**Comment by conroywhitney** [comment]
Same issue here. I created pull request #10 to fix this on OSX.

**Comment by joshkehn** [comment]
Also absolutely trivial to bypass the need to create a merge commit by examining `outputclue.sh`

**Comment by hgarc014** [comment]
added OS detection suggested by @issue-reporter  in #12 
Let me know if you have any other issues, thanks

**Comment by AnonJ** [comment]
It still didn't work on my OS X 10.10... even with the detection code in place. I'll try to see what happened in a while.
